updating deployment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -116,11 +116,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Setup SSH Key
-        run: |
-          echo "${{ secrets.SERVER_SSH_KEY }}" > private_key.pem
-          chmod 600 private_key.pem
-
       - name: Deploy to Server
         uses: appleboy/ssh-action@master
         with:
@@ -131,12 +126,19 @@ jobs:
             echo "🔄 Stopping existing container..."
             docker stop weather-app || true
             docker rm weather-app || true
-
+            
             echo "📥 Pulling latest image..."
             docker pull ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
-
+            
+            echo "🔍 Checking if 'weather-network' exists..."
+            if ! docker network inspect weather-network >/dev/null 2>&1; then
+              echo "⚠️ 'weather-network' not found. Creating it now..."
+              docker network create weather-network
+            else
+              echo "✅ 'weather-network' already exists."
+            fi
+            
             echo "🚀 Starting new container..."
             docker run -d -p 6161:6161 --name weather-app --network=weather-network ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
-
+            
             echo "✅ Deployment successful!"
-  
